Fix soxr detection in static builds
The Buildroot autobuilder detected a build [issue](http://autobuild.buildroot.org/results/53d/53d21686780aa2485745b59e812b6280dd39f1c5//shairport-sync-3.2.1/config.log) when building shairport-sync statically:

```
arm-buildroot-linux-uclibcgnueabi/sysroot/usr//lib/libsoxr.a(soxr.c.o): In function `soxr_create':
soxr.c:(.text+0xd4c): undefined reference to `av_get_cpu_flags'
collect2: error: ld returned 1 exit status
```

A quick look at the soxr source code shows that `soxr_create()` might use `av_get_cpu_flags()` under certain circumstances.

Therefore, add `-lavutil` to `[other-libraries]` when using
`AC_CHECK_LIB`.

Fixes: #733